services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 --timeout 120 app:app"  # Gunicorn command with worker count and binding to 0.0.0.0:5000
    pythonVersion: 3.9  # Or any version between 3.7 and 3.11
